### ISSUE TITLE
different behaviour running on Linux containers vs on windows

### ISSUE THREAD

**Issue by umbersar** [microsoft/sqlworkshops-sql2019workshop#2]
For the notebook https://github.com/microsoft/sqlworkshops-sql2019workshop/blob/master/sql2019workshop/04_Availability/adr/basic_adr.ipynb, the steps 3 and 4 give different results running on Linux containers vs on windows.

The 'used log space' percentage in step 3 and step 4 remains almost unchanged at 78% when i run it in a docker Linux container while if I run the same code on windows, the 'used log space' percentage drops from 91% to 79% going from step 3 to step 4. Why the difference in behaviour?

**Comment by rgward** [comment]
Not sure exactly the behavior on the container but that percentage difference is that important. The important factor is that the log is not truncated to a "low" number without ADR.
