### ISSUE TITLE
Missing steps/assets

### ISSUE THREAD

**Issue by stvflowers** [microsoft/sqlworkshops-sql2019workshop#5]
Section 02 - Intelligent Performance

Activity: SQL Server Intelligent Query Processing

"You have been provided a stored procedure called CustomerProfits"

This SP is nowhere to be found in WWI database.

There also is no "Facts" schema in WWI database.

**Comment by rgward** [comment]
Sorry I have not replied to this all of this year. The SP is found in the scripts as part of the activity. This was described in the activities

All scripts for this activity can be found in the sql2019workshop\02_IntelligentPerformance\iqp folder.
